name: dexter_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_datepicker: ^21.2.3
  syncfusion_flutter_sliders: ^21.2.4
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.2
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.2.1
  google_sign_in: ^6.1.4
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  flutter_svg: ^2.0.5
  file_picker: ^6.1.1
  camera: ^0.10.5+2
  intl: ^0.19.0
  dio: ^5.2.0+1
  path: ^1.8.2
  provider: ^6.1.1
  cinetpay: ^1.0.7
  firebase_core: ^2.25.3
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^16.3.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/dexter_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/moyensdepaiements/
    - assets/gifs/
